name: 'robomesh'
version: '0.1.0'
config-version: 2

profile: 'robomesh'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  robomesh:
    +materialized: view
    silver:
      +materialized: table
      +schema: silver
      +contract:
        enforced: true
    gold:
      +materialized: table
      +schema: gold
      +contract:
        enforced: true
